=== SerbiaStrong-220/space-station-14/Schemas/rsi.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "default": {},
    "description": "JSON Schema for SS14 RSI validation.",
    "examples": [
        {
            "version": 1,
            "license": "CC-BY-SA-3.0",
            "copyright": "Taken from CODEBASE at COMMIT PERMALINK",
            "size": {
                "x": 32,
                "y": 32
            },
            "states": [
                {
                    "name": "basic"
                },
                {
                    "name": "basic-directions",
                    "directions": 4
                },
                {
                    "name": "basic-delays",
                    "delays": [
                        [
                            0.1,
                            0.1
                        ]
                    ]
                },
                {
                    "name": "basic-delays-directions",
                    "directions": 4,
                    "delays": [
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ]
                    ]
                }
            ]
        }
    ],
    "required": [
        "version",
        "license",
        "copyright",
        "size",
        "states"
    ],
    "title": "RSI Schema",
    "type": "object",
    "properties": {
        "version": {
            "$id": "#/properties/version",
            "default": "",
            "description": "RSI version integer.",
            "title": "The version schema",
            "type": "integer"
        },
        "license": {
            "$id": "#/properties/license",
            "default": "",
            "description": "The license for the associated icon states. Restricted to SS14-compatible asset licenses.",
            "enum": [
                "CC-BY-3.0",
                "CC-BY-4.0",
                "CC-BY-SA-3.0",
                "CC-BY-SA-4.0",
                "CC-BY-NC-3.0",
                "CC-BY-NC-4.0",
                "CC-BY-NC-SA-3.0",
                "CC-BY-NC-SA-4.0",
                "CC0-1.0",
				"OFL",
				"EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
                "Custom"
            ],
            "examples": [
                "CC-BY-SA-3.0"
            ],
            "title": "License",
            "type": "string"
        },
        "copyright": {
            "$id": "#/properties/copyright",
            "title": "Copyright Info",
            "description": "The copyright holder. This is typically a link to the commit of the codebase that the icon is pulled from.",
            "default": "",
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ],
            "examples": [
                "Taken from CODEBASE at COMMIT LINK",
                [
                    "(License-1) First Author",
                    "(License-2) Second Author"
                ]
            ]
        },
        "size": {
            "$id": "#/properties/size",
            "default": {},
            "description": "The dimensions of the sprites inside the RSI.  This is not the size of the PNG files that store the sprite sheet.",
            "examples": [
                {
                    "x": 32,
                    "y": 32
                }
            ],
            "title": "Sprite Dimensions",
            "required": [
                "x",
                "y"
            ],
            "type": "object",
            "properties": {
                "x": {
                    "$id": "#/properties/size/properties/x",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                },
                "y": {
                    "$id": "#/properties/size/properties/y",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                }
            },
            "additionalProperties": true
        },
        "states": {
            "$id": "#/properties/states",
            "type": "array",
            "title": "Icon States",
            "description": "Metadata for icon states. Includes name, directions, delays, etc.",
            "default": [],
            "examples": [
                [
                    {
                        "name": "basic"
                    },
                    {
                        "name": "basic-directions",
                        "directions": 4
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/states/items",
                "type": "object",
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "directions": {
                        "type": "integer",
                        "enum": [
                            1,
                            4,
                            8
                        ]
                    },
                    "delays": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        }
    },
    "additionalProperties": true
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Structures/Specific/bags.rsi/meta.json
{
  "version": 1,
  "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
  "copyright": "Made by gabova (Discord) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "bagpile1"
    },
    {
      "name": "bagpile2"
    },
    {
      "name": "bagpile3"
    },
    {
      "name": "bagpile4"
    },
    {
      "name": "bagpile5"
    },
    {
      "name": "bagpile6"
    },
    {
      "name": "bagpile7"
    },
    {
      "name": "bagpile8"
    },
    {
      "name": "bagpile9"
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/Structures/Windows/reinforced_window.rsi/meta.json
{
  "version": 1,
  "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
  "copyright": "Made by MIXnikita for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "full"
    },
    {
      "name": "rwindow0",
      "directions": 4
    },
    {
      "name": "rwindow1",
      "directions": 4
    },
    {
      "name": "rwindow2",
      "directions": 4
    },
    {
      "name": "rwindow3",
      "directions": 4
    },
    {
      "name": "rwindow4",
      "directions": 4
    },
    {
      "name": "rwindow5",
      "directions": 4
    },
    {
      "name": "rwindow6",
      "directions": 4
    },
    {
      "name": "rwindow7",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Effects/cult_yogg_cleansing.rsi/meta.json
{
    "version": 1,
    "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
    "copyright": "Made by Mixnikita for SS220",
    "size": {
        "x": 32,
        "y": 32
    },
    "states": [
        {
            "name": "cleansingEffect",
            "delays": [
                [
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15,
                    0.15
                ]
            ]
        }
    ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/Neck/Cloaks/centcomm_fo.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/5a73e8f825ff279e82949b9329783a9e3070e2da, sprites in hand by PuroSlavKing (Github) and RudeyCoolLeet#3875, colors edited by noctyrnal (github) modified by MrALPAKA for SS220, colors edited by EstKemran (Github) for SS220, resomi states sprited by abubben (Discord) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "equipped-NECK",
      "directions": 4
    },
	  {
      "name": "equipped-NECK-resomi",
      "directions": 4
    },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/Head/Helmets/spaceninja.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Taken from TG Station https://github.com/tgstation/tgstation/blob/HEAD/icons/mob/clothing/modsuit/mod_clothing.dmi, vox state taken from Skyrat TG Station https://github.com/Skyrat-SS13/Skyrat-tg/blob/HEAD/modular_skyrat/modules/better_vox/icons/clothing/mod.dmi",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "icon-flash"
    },
    {
      "name": "off-equipped-HELMET",
      "directions": 4
    },
    {
      "name": "off-equipped-HELMET-vox",
      "directions": 4
    },
    {
      "name": "on-equipped-HELMET",
      "directions": 4
    },
    {
      "name": "on-equipped-HELMET-vox",
      "directions": 4
    },
    {
      "name": "off-inhand-left",
      "directions": 4
    },
    {
      "name": "off-inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Clothing/Uniforms/Jumpsuit/qm.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/c838ba21dae97db345e0113f99596decd1d66039, edited by Flareguy. In hand sprite scaled down by potato1234_x, monkey made by brainfood1183 (github) for ss14, Resprited by Kit0vras (Github), tie-equipped-INNERCLOTHING and icon_tie made by dinazewwr for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "icon_tie"
    },
    {
      "name": "equipped-INNERCLOTHING",
      "directions": 4
    },
    {
      "name": "tie-equipped-INNERCLOTHING",
      "directions": 4
    },
    {
      "name": "equipped-INNERCLOTHING-monkey",
      "directions": 4
    },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Objects/Misc/holocigar.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "By okroshka14",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
      {
      "name": "equipped-MASK",
      "directions": 4,
      "delays": [
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ]
      ]
    },
    {
    "name": "icon",
    "delays": [
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ]
      ]
    },
    {
      "name": "inhand-left",
      "directions": 4,
      "delays": [
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ]
      ]
    },
    {
      "name": "inhand-right",
      "directions": 4,
      "delays": [
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ],
        [
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1,
          0.1
        ]
      ]
    }
]
}

=== SerbiaStrong-220/space-station-14/Resources/Textures/SS220/Objects/Misc/business_card.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "By Aserovich, modified by Estkemran (Github) for SS220",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "iaa_card"
    },
    {
      "name": "law_card"
    },
    {
      "name": "magistrate_card"
    }
  ]
}
